<?php  
 $this->contentPane()->captureStart('appWorkSpace', array('region' => 'center', 'parseOnLoad' => true));
 echo $this->layout()->content; 
 echo $this->contentPane()->captureEnd('appWorkSpace'); 
?>
<?php  
//$this->borderContainer()->captureStart('appWorkSpace', array('region' => 'center'), array()); 
//echo $this->layout()->content;
//echo $this->borderContainer()->captureEnd('appWorkSpace');
?>

