<?php
echo $this->doctype();
?>
<html>
<head>
        <?php
            echo $this->headMeta();
            echo $this->headTitle('SipOasis');
        ?>
        <?php 
        echo $this->headLink()
                ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
                ->headLink()
                ->appendStylesheet('/skins/default/style.css', 'screen');
        ?>
<script>
dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	has: {
       "dojo-firebug": true,
       "dojo-debug-messages": true
	},
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	],
	app: {

	},
	// Get "fresh" resources
	cacheBust: true
};
</script>

<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js"></script>
<script type="text/javascript">
require([
  "aurora/app",
]);
</script>
</head>
<body class="claro">
	<div data-dojo-type="dijit/layout/BorderContainer" design="headline" gutters="true" style="z-index: 0; width: 100%; height: 100%;">
		<div data-dojo-id="headerPane" data-dojo-type="dijit/layout/ContentPane" region="top" splitter="true">
		<?php 
		echo $this->navigation()->menu();
		?>
		</div>
		
		<div data-dojo-id="bodyContentPanel" data-dojo-type="dijit/layout/ContentPane" region="center" splitter="false">
		  <?php 
            echo $this->layout()->content;
          ?>
		</div>
		<div data-dojo-id="footerPane" data-dojo-type="dijit/layout/ContentPane" region="bottom" splitter="true">
		Site Footer
		</div>
	</div>
    </body>
</html>