Default
<div class="ui-widget-content ui-helper-clearfix">
	<div class="grid_8">
		<?php
		if(isset($this->form)) {
		?>
		<?php //echo strtoupper($this->form->getName()); ?>
			<?php
			if(isset($this->messages) || isset($this->message)) {
				if(is_array($this->messages)) {
					echo '<span>', implode($this->messages) ,'</span>';
				}
				else {
					echo $this->message;
			}
		}
		echo $this->form;
		}
		?>
	</div>
</div>
